{
    "levelname": "INFO",
    "asctime": "2023-11-01 19:16:57,952",
    "message": "C:\\Users\\KeshavAgrawal\\Desktop\\Hospital-Management-Api\\Hospital-Management-Api\\hospital_management\\settings.py changed, reloading.",
    "filename": "autoreload.py",
    "taskName": null
}
{
    "levelname": "INFO",
    "asctime": "2023-11-01 19:16:59,396",
    "message": "Watching for file changes with StatReloader",
    "taskName": null
}
{
    "levelname": "INFO",
    "asctime": "2023-11-01 19:17:16,790",
    "message": "Watching for file changes with StatReloader",
    "taskName": null
}
{
    "levelname": "INFO",
    "asctime": "2023-11-01 19:20:20,806",
    "message": "Watching for file changes with StatReloader",
    "taskName": null
}
{
    "levelname": "INFO",
    "asctime": "2023-11-01 19:21:10,270",
    "message": "C:\\Users\\KeshavAgrawal\\Desktop\\Hospital-Management-Api\\Hospital-Management-Api\\hospital_management\\settings.py changed, reloading.",
    "taskName": null
}
{
    "levelname": "INFO",
    "asctime": "2023-11-01 19:21:11,641",
    "message": "Watching for file changes with StatReloader",
    "filename": "autoreload.py",
    "taskName": null
}
{
    "levelname": "INFO",
    "asctime": "2023-11-01 19:22:51,673",
    "message": "Watching for file changes with StatReloader",
    "filename": "autoreload.py",
    "taskName": null
}
{
    "levelname": "INFO",
    "asctime": "2023-11-01 19:23:38,766",
    "message": "Watching for file changes with StatReloader",
    "filename": "autoreload.py",
    "taskName": null
}
{
    "levelname": "ERROR",
    "asctime": "2023-11-01 19:24:33,380",
    "message": "Internal Server Error: /api/patient/fs/",
    "filename": "log.py",
    "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\fields\\__init__.py\", line 2649, in to_python\n    return uuid.UUID(**{input_form: value})\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\uuid.py\", line 178, in __init__\n    raise ValueError('badly formed hexadecimal UUID string')\nValueError: badly formed hexadecimal UUID string\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 55, in wrapped_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\viewsets.py\", line 125, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\Desktop\\Hospital-Management-Api\\Hospital-Management-Api\\patient\\views.py\", line 23, in retrieve\n    data = list(Patient.objects.filter(patient_id = kwargs['pk']).values())\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1421, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1439, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1446, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1532, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n                                 ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1478, in build_filter\n    condition = self.build_lookup(lookups, col, value)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1303, in build_lookup\n    lookup = lookup_class(lhs, rhs)\n             ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\lookups.py\", line 27, in __init__\n    self.rhs = self.get_prep_lookup()\n               ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\lookups.py\", line 341, in get_prep_lookup\n    return super().get_prep_lookup()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\lookups.py\", line 85, in get_prep_lookup\n    return self.lhs.output_field.get_prep_value(self.rhs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\fields\\__init__.py\", line 2633, in get_prep_value\n    return self.to_python(value)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KeshavAgrawal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\db\\models\\fields\\__init__.py\", line 2651, in to_python\n    raise exceptions.ValidationError(\ndjango.core.exceptions.ValidationError: ['\u201cfs\u201d is not a valid UUID.']",
    "taskName": null,
    "status_code": 500,
    "request": "<WSGIRequest: GET '/api/patient/fs/'>"
}